### ISSUE TITLE
Create Django test cases for all API endpoints

### ISSUE THREAD

**Issue by nishant-nayak** [iHART-NITK/backend#3]
## Tasks

- [ ] Create Test classes for each functionality
- [ ] Create Test functions for each request type (GET, POST, PUT, DELETE, etc.)
- [ ] Verify they work using `python manage.py test`

## Resources

- [Django Rest Framework Testing](https://www.django-rest-framework.org/api-guide/testing/#api-test-cases)
