### ISSUE TITLE
Create custom API endpoints for different functionalities

### ISSUE THREAD

**Issue by nishant-nayak** [iHART-NITK/backend#4]
## Tasks

- [ ] Identify the functionalities that require custom API endpoints
- [ ] Fetch the data appropriately from the database on the backend
- [ ] Create unique API endpoints to access these resources 

## Resources

- [Functionalities from the SRS](https://docs.google.com/document/d/1XGywyya7vvptbruyzvEyF1Qv_eH-kcrZwKIZgxUOmdU/edit#heading=h.yvw2zoxg9x5o)
