### ISSUE TITLE
Implement CSRF Verification for all POST Requests

### ISSUE THREAD

**Issue by nishant-nayak** [iHART-NITK/backend#5]
## Tasks

 - [ ] Find all functions where POST requests will be made to the API
 - [ ] Create and send a CSRF Token when the API is accessed using the GET request
 - [ ] Validate the POST request using the received CSRF token

## Dependencies

- Frontend will have to add the CSRF Token in the POST request (need to add the field in all form bodies)
