### ISSUE TITLE
Make new "create" endpoints to create new resources + extra tasks

### ISSUE THREAD

**Issue by nishant-nayak** [iHART-NITK/backend#9]
## Tasks

- [x] For existing CRUD endpoints, remove the POST method from the default `<resource>/<int:pk>` route
- [x] Make a new endpoint with the URL `<resource>/create` or `<resource>/new` that only accepts POST requests. This endpoint should create a new entry of the resource in the database.
- [x] **Extra Task 1**: For models like MedicalHistory, ensure that `objects.filter(id=pk)` is being used instead of `objects.get(id=pk)`. This issue needs to be resolved for all models that can have multiple entries for a single user.
- [x] **Extra Task 2**: Create an additional endpoint that retrieves all the location options for an emergency (can be fetched using `Emergency.LOCATION_CHOICES`
